TEAM_DATA = {
    "MI": {"name": "Mumbai Indians", "fullName": "Mumbai Indians", "owner": "Reliance Industries", "coach": "Mark Boucher", "captain": "Hardik Pandya", "homeGround": "Wankhede Stadium, Mumbai", "founded": "2008", "titles": 5, "matches": 245, "winRate": "58%", "bgClass": "bg-mi", "keyPlayers": ["Hardik Pandya", "Rohit Sharma", "Jasprit Bumrah", "Suryakumar Yadav"]},
    "CSK": {"name": "Chennai Super Kings", "fullName": "Chennai Super Kings", "owner": "Chennai Super Kings Cricket Ltd.", "coach": "Stephen Fleming", "captain": "Ruturaj Gaikwad", "homeGround": "M.A. Chidambaram Stadium, Chennai", "founded": "2008", "titles": 5, "matches": 235, "winRate": "59%", "bgClass": "bg-csk", "keyPlayers": ["Ruturaj Gaikwad", "Ravindra Jadeja", "Deepak Chahar", "Shivam Dube"]},
    "RCB": {"name": "Royal Challengers Bengaluru", "fullName": "Royal Challengers Bengaluru", "owner": "United Spirits", "coach": "Andy Flower", "captain": "Faf du Plessis", "homeGround": "M. Chinnaswamy Stadium, Bengaluru", "founded": "2008", "titles": 0, "matches": 236, "winRate": "48%", "bgClass": "bg-rcb", "keyPlayers": ["Virat Kohli", "Faf du Plessis", "Glenn Maxwell", "Mohammed Siraj"]},
    "KKR": {"name": "Kolkata Knight Riders", "fullName": "Kolkata Knight Riders", "owner": "Knight Riders Group", "coach": "Chandrakant Pandit", "captain": "Shreyas Iyer", "homeGround": "Eden Gardens, Kolkata", "founded": "2008", "titles": 2, "matches": 230, "winRate": "51%", "bgClass": "bg-kkr", "keyPlayers": ["Shreyas Iyer", "Andre Russell", "Sunil Narine", "Rinku Singh"]},
    "SRH": {"name": "Sunrisers Hyderabad", "fullName": "Sunrisers Hyderabad", "owner": "Sun TV Network", "coach": "Brian Lara", "captain": "Pat Cummins", "homeGround": "Rajiv Gandhi International Stadium, Hyderabad", "founded": "2012", "titles": 1, "matches": 183, "winRate": "49%", "bgClass": "bg-srh", "keyPlayers": ["Pat Cummins", "Travis Head", "Abhishek Sharma", "Heinrich Klaasen"]},
    "DC": {"name": "Delhi Capitals", "fullName": "Delhi Capitals", "owner": "JSW Sports and GMR Sports", "coach": "Ricky Ponting", "captain": "Rishabh Pant", "homeGround": "Arun Jaitley Stadium, Delhi", "founded": "2008", "titles": 0, "matches": 252, "winRate": "45%", "bgClass": "bg-dc", "keyPlayers": ["Rishabh Pant", "David Warner", "Axar Patel", "Kuldeep Yadav"]},
    "PBKS": {"name": "Punjab Kings", "fullName": "Punjab Kings", "owner": "KPH Dream Cricket Private Limited", "coach": "Trevor Bayliss", "captain": "Shikhar Dhawan", "homeGround": "PCA Stadium, Mohali", "founded": "2008", "titles": 0, "matches": 252, "winRate": "44%", "bgClass": "bg-pbks", "keyPlayers": ["Shikhar Dhawan", "Sam Curran", "Arshdeep Singh", "Liam Livingstone"]},
    "RR": {"name": "Rajasthan Royals", "fullName": "Rajasthan Royals", "owner": "Royal Multisport Private Limited", "coach": "Kumar Sangakkara", "captain": "Sanju Samson", "homeGround": "Sawai Mansingh Stadium, Jaipur", "founded": "2008", "titles": 1, "matches": 220, "winRate": "49%", "bgClass": "bg-rr", "keyPlayers": ["Sanju Samson", "Jos Buttler", "Yashasvi Jaiswal", "Ravichandran Ashwin"]},
    "GT": {"name": "Gujarat Titans", "fullName": "Gujarat Titans", "owner": "CVC Capital Partners", "coach": "Ashish Nehra", "captain": "Shubman Gill", "homeGround": "Narendra Modi Stadium, Ahmedabad", "founded": "2022", "titles": 1, "matches": 46, "winRate": "65%", "bgClass": "bg-gt", "keyPlayers": ["Shubman Gill", "Rashid Khan", "Mohammed Shami", "David Miller"]},
    "LSG": {"name": "Lucknow Super Giants", "fullName": "Lucknow Super Giants", "owner": "RPSG Group", "coach": "Justin Langer", "captain": "KL Rahul", "homeGround": "BRSABVE Cricket Stadium, Lucknow", "founded": "2022", "titles": 0, "matches": 44, "winRate": "57%", "bgClass": "bg-lsg", "keyPlayers": ["KL Rahul", "Nicholas Pooran", "Ravi Bishnoi", "Ayush Badoni"]}
}
